import adminBroRoute from "./admin/adminBro";
import authRouter from "./auth/auth.router";
import express from "express";
import lectureRouter from "./material/lecture.router";
import materialRouter from "./material/material.router";
import profileRouter from "./profile/profile.router";
import studentsRouter from "./student/student.router";
import submissionRouter from "./submission/submission.router";
import tasksRouter from "./tasks/tasks.router";
import trackRouter from "./track/track.router";
import router from "./auth/auth.router";
const routers = express.Router();

routers.use(authRouter);
routers.use("/profile", profileRouter);
routers.use("/admin", adminBroRoute);
routers.use("/students", studentsRouter);
routers.use("/lectures", lectureRouter);
routers.use("/material", materialRouter);
routers.use("/track", trackRouter);
routers.use(submissionRouter);
routers.use(tasksRouter);
export default routers;
